title: #
description: #
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
theme: # or any other theme you want to use
markdown: kramdown # specify the markdown processor
